# ./docker-compose.yml

version: "3"

services:
  db:
    image: mariadb:10
    container_name: tennis-db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: tennis
      MYSQL_USER: tennis_user
      MYSQL_PASSWORD: tennis_password
    volumes:
      - ./mysql-data:/var/lib/mysql/
    ports:
      - "9906:3306"
    user: mysql

  phpmyadmin:
    depends_on:
      - db
    container_name: tennis-pma
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8101:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh

  www:
    depends_on:
      - db
    #    image: php:7.3-apache
    build:
      context: ./tecla-php
    container_name: tennis-www
    volumes:
      - ../src/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
